;;; default.el --- Package lockfile for SEM Assistant -*- lexical-binding: t; -*-

;;; Commentary:
;; This lockfile pins exact package revisions for reproducible builds.
;; Generated by straight.el. Do not edit manually.
;; Update by running: M-x straight-pull-package RET <package> RET

;;; Code:

(straight-use-package 'gptel :pin "a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2")
(straight-use-package 'elfeed :pin "b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3")
(straight-use-package 'elfeed-org :pin "c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4")
(straight-use-package 'org-roam :pin "d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5")
(straight-use-package 'websocket :pin "e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6")

(provide 'default)
;;; default.el ends here
