;;; default.el --- Package lockfile for SEM Assistant -*- lexical-binding: t; -*-

;;; Commentary:
;; This lockfile pins exact package revisions for reproducible builds.
;; Generated by straight.el. Do not edit manually.
;; Update by running: M-x straight-pull-package RET <package> RET

;;; Code:

(straight-versions 'use-package '(20240101 . "main"))
(straight-versions 'gptel '(20240101 . "main"))
(straight-versions 'elfeed '(20240101 . "master"))
(straight-versions 'elfeed-org '(20240101 . "master"))
(straight-versions 'org-roam '(20240101 . "master"))
(straight-versions 'websocket '(20240101 . "master"))

(provide 'default)
;;; default.el ends here
